[project]
name = "automation-portfolio"
version = "0.1.0"
description = ""
authors = [
    {name = "Marcelo Pinheiro",email = "marcelohenrique5620@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12, <3.13"
dependencies = [
    "robotframework",
    "robotframework-browser (>=19.6.0,<20.0.0)",
    "requests (>=2.32.5,<3.0.0)"
]

[tool.poetry]
packages = [{include = "automation_portfolio", from = "src"}]

[tool.poetry.dependencies]
python = "^3.12"
robotframework = "*"
robotframework-browser = ">=19.6.0,<20.0.0"
requests = ">=2.32.5,<3.0.0"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
