BROWSER_STRATEGY: incognito # persistent, incognito
WEB_BROWSER: chromium # chromium, firefox, webkit
BROWSER_IS_HEADLESS: false
BROWSER_TIMEOUT: 60
CHROME_ARGS: []
WEB_BROWSER_DOWNLOAD_PATH: ${EXECDIR}/Downloads
DEFAULT_WINDOW_RESOLUTION: FHD
CONTEXT_ARGUMENTS: {}

DISPLAY_RESOLUTION_DICT:
  MAX:
    WIDTH: 0
    HEIGHT: 0
    ASPECT_RATIO: null
  HD:
    WIDTH: 1280
    HEIGHT: 720
    ASPECT_RATIO: 16:9
  FHD:
    WIDTH: 1920
    HEIGHT: 1080
    ASPECT_RATIO: 16:9
  QUAD_HD:
    WIDTH: 2560
    HEIGHT: 1440
    ASPECT_RATIO: 16:9